services:
  django:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media:/code/media
    environment:
      - DJANGO_SETTINGS_MODULE=fabrik.settings
      - PORT=8000

volumes:
  static_volume:
  media: