# Generated by Django 5.1.2 on 2024-11-07 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_followerscount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followerscount',
            old_name='followers',
            new_name='follower',
        ),
    ]
